vscode/CHANGELOG.md
vscode/package.json
vscode/src/api/index/dependi-index-server/indexes.ts
vscode/src/api/index/go-proxy-server.ts
vscode/src/api/index/npm-index-server.ts
vscode/src/api/index/sparse-index-server.ts
vscode/src/api/utils.ts

10 version string name handling error

---

vscode/src/commands/report-generator/generateVulnerabilityReport.ts
vscode/src/commands/report-generator/gitActions.ts
vscode/src/commands/report-generator/reportGenerator.ts

Fixes vuln report generate command

fix: Fixes vuln report generate command

---

vscode/CHANGELOG.md
vscode/package.json

chore: Bump version to 0.7.3 in package.json

---

vscode/CHANGELOG.md
vscode/src/core/parsers/CargoTomlParser.ts
vscode/src/core/parsers/GoModParser.ts
vscode/src/core/parsers/PypiParser.ts
vscode/src/core/parsers/utils.ts

Req txt ignore improvement

---

vscode/CHANGELOG.md
vscode/README.md
vscode/package.json
vscode/src/config.ts
vscode/src/core/parsers/CargoTomlParser.ts
vscode/src/core/parsers/GoModParser.ts
vscode/src/core/parsers/JsonParser.ts
vscode/src/core/parsers/PypiParser.ts
vscode/src/core/parsers/utils.ts

feat: Update parsers to include ignore line pattern from settings

---

vscode/src/extension.ts

unused func deleted

---

vscode/CHANGELOG.md
vscode/package.json
vscode/src/api/index/dependi-index-server/reports.ts
vscode/src/commands/report-generator/generateCurrentVulnReport.ts
vscode/src/commands/report-generator/reportGenerator.ts
vscode/src/commands/report-generator/utils.ts
vscode/src/config.ts
vscode/src/extension.ts

feat: Added generate current vulnerability report command

---

vscode/CHANGELOG.md
vscode/src/semver/semverUtils.ts

60 python fails for the skyfield package

---

.github/workflows/vscode-publish.yml
vscode/src/core/fetchers/PypiFetcher.ts
vscode/src/semver/compareVersions.ts

Python prelease control and sorting fix

Add support for OpenVSX publishing

---

vscode/src/core/parsers/TomlParser.ts

fix: Update TomlParser to clear version values

---

vscode/src/core/parsers/PyProjectParser.ts
vscode/src/core/parsers/PypiParser.ts
vscode/src/semver/compareVersions.ts

Fixes version sorting function.
Fixes package version start index value.

fix: Fixed some python bugs

---

vscode/src/core/parsers/NpmParser.ts

closes https://github.com/filllabs/dependi/issues/63

refactor[npm]: Convert npm aliases to package names in NpmParser.ts

---

vscode/src/core/parsers/GoModParser.ts

fix: Add support for parsing single require lines in GoModParser

---

.gitignore
vscode/src/ui/decoration.ts

The lockfile value of the packages was used in the semver func

chore: The lockfile value of the packages was used in the semver func

---

vscode/CHANGELOG.md
vscode/src/extension.ts
vscode/src/panels/ChangelogPanel.ts
vscode/src/webviews/update-page.ts
vscode/src/webviews/utils.ts

update notification changed
changelog panel added

changelog cleanup

---

vscode/src/api/indexes/dependi/reports.ts
vscode/src/commands/report-generator/reportGenerator.ts

chore: Update vuln report Vulnreq

---

vscode/CHANGELOG.md
vscode/src/core/Item.ts

refactor: Improve validation logic in Item class

---

vscode/src/core/parsers/TomlLockParser.ts

refactor: Improve validation logic in TomlLockParser

---

vscode/src/api/indexes/npm.ts
vscode/src/commands/retry.ts
vscode/src/extension.ts

Clear cache only on specific config changes and retry command.

fix: Clear dependency cache

---

vscode/src/api/indexes/crates.ts
vscode/src/api/indexes/goproxy.ts
vscode/src/api/indexes/npm.ts
vscode/src/api/indexes/packagist.ts
vscode/src/api/indexes/pypi.ts
vscode/src/api/indexes/request.ts
vscode/src/api/indexes/utils.ts

Handled 3xx redirects by adding logic to follow the Location header.

fix: handle 3xx redirects properly

---

vscode/src/core/parsers/JsonParser.ts

Fixes handling of empty dependency fields to ensure correct processing.

refactor: Improve detection of dependencies in JsonParser

---

vscode/src/core/listeners/listener.ts
vscode/src/core/parsers/PypiParser.ts
vscode/src/semver/semverUtils.ts
vscode/src/ui/decoration.ts

Fixed some issues related to semver checks in Python packages. These issues were causing inconsistencies in version validation, which have now been resolved.
closes #161, #150

fix: Fixed python packages semver check bug

---

vscode/src/api/DepencencyInfo.ts
vscode/src/api/indexes/dependi/indexes.ts
vscode/src/api/indexes/npm.ts
vscode/src/core/fetchers/NpmFetcher.ts

This pull request addresses the issue of deprecated messages for npm packages. It includes updates and improvements to ensure that deprecated warnings are handled appropriately.
- Added logic for deprecated npm messages.

chore: Deprecated message handling in Npm

---

vscode/src/api/indexes/request.ts
vscode/src/config.ts

Issue #93
Add Protocol Options to request.ts for HTTP Support

issues #93 modified : http request Options

---

vscode/changelog.md
vscode/package.json

Reordered button groups to prioritize important buttons and hide less critical ones when space is limited. Improves UI consistency and usability.

Button navigation fix

---

vscode/changelog.md
vscode/src/api/indexes/goproxy.ts

**Description**:  
This PR addresses [Issue #210](https://github.com/filllabs/dependi/issues/210) by enhancing the Go dependency version parsing and retrieval process.  
- Fixed parsing issues in Go that were affecting version retrieval.  
- Added fallback to fetch the latest version when no versions are listed.  
These changes ensure more accurate and efficient version parsing and retrieval for Go dependencies.
https://go.dev/ref/mod#goproxy-protocol

Improve Go Dependency Version Parsing and Retrieval  

---

vscode/changelog.md
vscode/src/commands/report-generator/utils.ts
vscode/src/core/fetchers/fetcher.ts
vscode/src/semver/semverUtils.ts

Fixes incorrect SemVer compatibility checks during version comparison.

Fix: Incorrect SemVer compatibility checks
